MyWebApplication/Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApplication.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        German
    }
}

MyWebApplication/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MyWebApplication.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name ="Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }

    }
}

MyWebApplication/ViewModels/HomeIndexViewModel.cs
using MyWebApplication.Models;
using System.Collections.Generic;

namespace MyWebApplication.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

MyWebApplication/ViewModels/RestaurantEditModel.cs
using MyWebApplication.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApplication.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

MyWebApplication/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyWebApplication.Controllers
{
    [Route("[controller]/[action]")]
    public class AboutController
    {
        
        public string Phone()
        {
            return "1-988-999-9999";
        }

        
        public string Address()
        {
            return "USA";
        }
    }
}

MyWebApplication/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyWebApplication.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            var redirectUrl = Url.Page("/Index");
            return Challenge(
                new AuthenticationProperties { RedirectUri = redirectUrl },
                // challenge the user by logging in with OIDC server
                OpenIdConnectDefaults.AuthenticationScheme
            );
        }

        public IActionResult Logout()
        {
            var callbackUrl = Url.Page("/Account/SignedOut");
            return SignOut(
                new AuthenticationProperties { RedirectUri = callbackUrl },
                // remove cookie that authenticates user
                CookieAuthenticationDefaults.AuthenticationScheme,
                // also logout of OIDC identity provider
                OpenIdConnectDefaults.AuthenticationScheme
            );
        }
    }
}

MyWebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWebApplication.Models;
using MyWebApplication.Services;
using MyWebApplication.ViewModels;

namespace MyWebApplication.Controllers
{
    [Authorize] // checks to see if user is authenticated before any actions are made
    public class HomeController : Controller
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restaurantData,
                              IGreeter greeter)
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        [AllowAnonymous] // overrides authorization
        public IActionResult Index()
        {
            var model = new HomeIndexViewModel();
            model.Restaurants = _restaurantData.GetAll();
            model.CurrentMessage = _greeter.GetMessageOfTheDay();

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _restaurantData.Get(id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel model)
        {
            if(ModelState.IsValid)
            {
            var newRestaurant = new Restaurant();
            newRestaurant.Name = model.Name;
            newRestaurant.Cuisine = model.Cuisine;

            newRestaurant = _restaurantData.Add(newRestaurant);
            return RedirectToAction(nameof(Details), new { id=newRestaurant.Id});
            }
            else
            {
                return View();
            }
        }
    }
}

MyWebApplication/Pages/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyWebApplication.Pages.Account
{
    public class SignedOutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MyWebApplication/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyWebApplication.Services;

namespace MyWebApplication.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;

        public string CurrentGreeting { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public void OnGet(string name)
        {
            CurrentGreeting = $"{name}: {_greeter.GetMessageOfTheDay()}";
        }
    }
}

MyWebApplication/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyWebApplication.Models;
using MyWebApplication.Services;

namespace MyWebApplication.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);
            if (Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(Restaurant);
                return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
            }
            return Page();
        }
    }
}

MyWebApplication/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyWebApplication.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApplication.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();
            return View("Default", model);
        }
    }
}

MyWebApplication/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApplication.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

MyWebApplication/Pages/Account/SignedOut.cshtml
@page

<div>You are signed out.</div>
<a asp-controller="Home" asp-action="Index">Go Home</a>

MyWebApplication/Pages/Greeting.cshtml
@page "{name}"

@model GreetingModel

<div>@Model.CurrentGreeting</div>

MyWebApplication/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using MyWebApplication.Pages.Restaurants

@model EditModel

<h1>Editing @Model.Restaurant.Name</h1>

<form method="post">

    <input type="hidden" asp-for="Restaurant.Id" />

    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>

    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>

    </div>
    <input type="submit" name="save" value="Save" />
</form>

MyWebApplication/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
    </footer>
</body>
</html>

MyWebApplication/Views/Home/Create.cshtml
@using MyWebApplication.Models
@model Restaurant

@{ 
    ViewBag.title = "Create";
}
<h1>Create</h1>

<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>

    </div>

    <input type="submit" name="save" value="Save" />
</form>

MyWebApplication/Views/Home/Details.cshtml
@model Restaurant

@{ 
    ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>
<div>
    Id: @Model.Id
</div>
<div>
    Cuisine: @Model.Cuisine
</div>

<a asp-action="Index" asp-controller="Home">Home</a>

MyWebApplication/Views/Home/Index.cshtml
@model MyWebApplication.ViewModels.HomeIndexViewModel

@{
    ViewBag.Title = "Home page";
}

<h1>All Restaurants</h1>

@foreach (var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)
}

<div>
    <a class="btn btn-primary" asp-action="Create">Add Restaurant</a>
</div>

MyWebApplication/Views/Home/_Summary.cshtml
@model  Restaurant

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cuisine: @Model.Cuisine
    </div>
    <div class="panel-footer">
        <a class="btn btn-default" asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

MyWebApplication/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

MyWebApplication/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <div>Hello, @User.Identity.Name</div>
    <a class="btn btn-default" asp-controller="Account" asp-action="Logout">Logout</a>
}
else
{
    <a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>
}

MyWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OdeToFood</a>
            </div>
            <div class="navbar-right">
                <vc:login-logout></vc:login-logout>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
        </footer>
    </div>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9kz8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
    </environment>
</body>
</html>